name: dsc180
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pandas==2.1.4
  - numpy==1.26.2
  - pytorch==2.1.1
  - tqdm==4.66.1
  - transformers==4.35.0
  - scikit-learn==1.3.2
  - seaborn==0.13.0
  - matplotlib==3.8.2
  - pyarrow==12.0.0
  - statistics==1.0.3.5
